language: php

php:
    - 7.1

install:
    - travis_retry composer install --no-interaction --no-suggest

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit